version: '3.6'

include:    
  - path: ./validators.yml
  #- path: ./monitoring.yml
  #- path: ./interaction-layer.yml

networks:
  quorum-network:
    name: quorum-network
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  splunk:
  ethlogger:
  prometheus:
  grafana:
  blockscoutpostgres:
