version: '3.4'

services:
  api0:
    container_name: api0
    image: vbrnds/ipfs-eth-api:latest
    depends_on:
    - validator0
    expose:
    - '5003'
    environment:
      ETH_HOST: http://validator0:8545
      ETH_HOST_WS: ws://validator0:8546
      IPFS_HOST: http://ipfs0:5001
      KEYSTORE_PASSWORD: password
      SMART_CONTRACT_VERSION: onchain
      VERSION_API: onchain
      CONTRACT_ADDR: '0x080c7091CB3769c98898a854aABf113DF9857b32'
      IPFS_CLUSTER_API: http://cluster0:9094
      CHAIN_ID: '1337'
    networks:
      quorum-network: {}
  nginx:
    image: nginx:latest
    volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - api0
    - api1
    - api2
    - api3
    ports:
    - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500MB
    networks:
      quorum-network: {}
  api1:
    container_name: api1
    image: vbrnds/ipfs-eth-api:latest
    depends_on:
    - validator1
    expose:
    - '5003'
    environment:
      ETH_HOST: http://validator1:8545
      ETH_HOST_WS: ws://validator1:8546
      IPFS_HOST: http://ipfs1:5001
      KEYSTORE_PASSWORD: password
      SMART_CONTRACT_VERSION: onchain
      VERSION_API: onchain
      CONTRACT_ADDR: '0x080c7091CB3769c98898a854aABf113DF9857b32'
      IPFS_CLUSTER_API: http://cluster1:9094
      CHAIN_ID: '1337'
    networks:
      quorum-network: {}
  api2:
    container_name: api2
    image: vbrnds/ipfs-eth-api:latest
    depends_on:
    - validator2
    expose:
    - '5003'
    environment:
      ETH_HOST: http://validator2:8545
      ETH_HOST_WS: ws://validator2:8546
      IPFS_HOST: http://ipfs2:5001
      KEYSTORE_PASSWORD: password
      SMART_CONTRACT_VERSION: onchain
      VERSION_API: onchain
      CONTRACT_ADDR: '0x080c7091CB3769c98898a854aABf113DF9857b32'
      IPFS_CLUSTER_API: http://cluster2:9094
      CHAIN_ID: '1337'
    networks:
      quorum-network: {}
  api3:
    container_name: api3
    image: vbrnds/ipfs-eth-api:latest
    depends_on:
    - validator3
    expose:
    - '5003'
    environment:
      ETH_HOST: http://validator3:8545
      ETH_HOST_WS: ws://validator3:8546
      IPFS_HOST: http://ipfs3:5001
      KEYSTORE_PASSWORD: password
      SMART_CONTRACT_VERSION: onchain
      VERSION_API: onchain
      CONTRACT_ADDR: '0x080c7091CB3769c98898a854aABf113DF9857b32'
      IPFS_CLUSTER_API: http://cluster3:9094
      CHAIN_ID: '1337'
    networks:
      quorum-network: {}
