
version: '3.6'


# x-chainlensapi-ref:
#   &chainlensapi-def
#   image: web3labs/epirus-free-api:latest
#   container_name: chainlensapi
#   environment:
#     - NODE_ENDPOINT=http://rpcnode:8545
#     - MONGO_CLIENT_URI=mongodb://chainlensmongodb:27017
#     - REINDEX_ENDPOINT=http://chainlensingestion/reindex/
#     - MONGO_DB_NAME=epirus
#     - MONGO_CREATE_INDICES=true
#   depends_on:
#     - chainlensmongodb

# x-chainlensmongodb-ref:
#   &chainlensmongodb-def
#   image: mongo:5.0.8
#   container_name: chainlensmongodb
#   environment:
#     - COMPOSE_HTTP_TIMEOUT=900
#     - DOCKER_CLIENT_TIMEOUT=900
#   entrypoint: mongod --bind_ip "0.0.0.0"

# x-chainlensweb-ref:
#   &chainlensweb-def
#   image: web3labs/epirus-free-web:latest
#   container_name: chainlensweb
#   environment:
#     - API_URL=/api
#     - DISPLAY_NETWORK_TAB=disabled
#   depends_on:
#     - chainlensapi

# x-chainlensingestion-ref:
#   &chainlensingestion-def
#   image: web3labs/epirus-free-ingestion:latest
#   container_name: chainlensingestion
#   environment:
#     - NODE_ENDPOINT=http://rpcnode:8545
#     - MONGO_CLIENT_URI=mongodb://chainlensmongodb:27017
#     - MONGO_DB_NAME=epirus
#   depends_on:
#     - chainlensmongodb
#     - chainlensweb

# x-chainlensnginx-ref:
#   &chainlensnginx-def
#   image: nginx:latest
#   container_name: chainlensnginx
#   volumes:
#     - ./compose-data/chainlens/nginx.conf:/etc/nginx/nginx.conf
#     - ./compose-data/chainlens/5xx.html:/www/error_pages/5xx.html
#   ports:
#     - 8081:80
#   depends_on:
#     - chainlensapi
#     - chainlensweb

services:
  # chainlensapi:
  #   <<: *chainlensapi-def
  #   networks:
  #     quorum-network:
  #       ipv4_address: 172.16.239.153

  # chainlensmongodb:
  #   <<: *chainlensmongodb-def
  #   networks:
  #     quorum-network:
  #       ipv4_address: 172.16.239.154

  # chainlensingestion:
  #   <<: *chainlensingestion-def
  #   depends_on:
  #     - rpcnode
  #   networks:
  #     quorum-network:
  #       ipv4_address: 172.16.239.155

  # chainlensweb:
  #   <<: *chainlensweb-def
  #   networks:
  #     quorum-network:
  #       ipv4_address: 172.16.239.156

  # chainlensnginx:
  #   <<: *chainlensnginx-def
  #   networks:
  #     quorum-network:
  #       ipv4_address: 172.16.239.157

  # explorer:
  #   image: consensys/quorum-explorer:${QUORUM_EXPLORER_VERSION:-latest}
  #   volumes:
  #     - ./compose-data/quorum-explorer/config.json:/app/config.json
  #     - ./compose-data/quorum-explorer/env:/app/.env.production
  #   depends_on:
  #     - rpcnode
  #   ports:
  #     - 25000:25000/tcp
  #   networks:
  #     quorum-network:
  #       ipv4_address: 172.16.239.230

  prometheus:
    image: "prom/prometheus:v2.46.0"
    volumes:
      - ./compose-data/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml 
    ports:
      - 9090:9090/tcp
    networks:
      quorum-network:
        ipv4_address: 172.16.239.231

  grafana:
    image: "grafana/grafana:10.1.0"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_VIEWERS_CAN_EDIT=true
    volumes:
      - ./compose-data/config/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp
    depends_on:
      - prometheus
    networks:
      quorum-network:
        ipv4_address: 172.16.239.232

  loki:
    image: "grafana/loki:2.8.4"
    volumes:
      - ./compose-data/loki/loki.yml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100/tcp
    networks:
      quorum-network:
        ipv4_address: 172.16.239.233

  promtail:
    image: "grafana/promtail:2.8.4"
    volumes:
      - ./compose-data/logs:/var/log
      - ./compose-data/promtail/promtail.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - rpcnode
    networks:
      quorum-network:
        ipv4_address: 172.16.239.234

