FROM golang:1.21-alpine AS base


RUN apk add -U tzdata
RUN apk --update add ca-certificates

WORKDIR /app
COPY . .

RUN go mod download
RUN go mod verify

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64

RUN go build -ldflags="-s -w" -o /server ./api/main.go

EXPOSE 5003

CMD [ "/server" ]