version: "3.4"

services:
  api0:
    container_name: api0
    image: vbrnds/ipfs-eth-api:latest
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api0
      - api1
      - api2
      - api3
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "500MB"